# Generated by Django 5.2 on 2025-04-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecandy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductNo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
