# Generated by Django 5.2 on 2025-04-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecandy', '0002_alter_product_productno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='icecandy.OrderItem', to='icecandy.product'),
        ),
    ]
